# Generated by Django 5.2.5 on 2025-09-01 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('exchange', models.CharField(max_length=10)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='股票代碼')),
                ('alert_type', models.CharField(choices=[('above', '高於'), ('below', '低於'), ('change_percent', '漲跌幅')], max_length=20, verbose_name='提醒類型')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='目標值')),
                ('status', models.CharField(choices=[('active', '啟用'), ('triggered', '已觸發'), ('disabled', '停用')], default='active', max_length=20, verbose_name='狀態')),
                ('message', models.TextField(blank=True, verbose_name='提醒訊息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='觸發時間')),
                ('triggered_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='觸發價格')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '價格提醒',
                'verbose_name_plural': '價格提醒',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('average_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolios.portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('change_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('volume', models.BigIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='portfolios.stock')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分組名稱')),
                ('description', models.TextField(blank=True, verbose_name='分組描述')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='分組顏色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('order', models.IntegerField(default=0, verbose_name='排序順序')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '自選股分組',
                'verbose_name_plural': '自選股分組',
                'ordering': ['order', 'created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='股票代碼')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='添加時間')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='目標價格')),
                ('stop_loss_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='停損價格')),
                ('alert_enabled', models.BooleanField(default=False, verbose_name='價格提醒啟用')),
                ('order', models.IntegerField(default=0, verbose_name='排序順序')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='portfolios.watchlistgroup')),
            ],
            options={
                'verbose_name': '自選股',
                'verbose_name_plural': '自選股',
                'ordering': ['order', 'added_at'],
                'unique_together': {('user', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='WatchlistStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.stock')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_stocks', to='portfolios.watchlist')),
            ],
            options={
                'unique_together': {('watchlist', 'stock')},
            },
        ),
    ]
