# Generated by Django 5.2.5 on 2025-09-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
    ]
